# Generated by Django 5.0 on 2023-12-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Описание')),
                ('departure', models.TextField(verbose_name='Откуда')),
                ('destination', models.TextField(verbose_name='Куда')),
                ('del_time', models.IntegerField(verbose_name='Срок доставки (Дни)')),
                ('volume', models.FloatField(verbose_name='Объем (куб.м)')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('is_danger', models.BooleanField(verbose_name='Опасен')),
                ('conditions', models.TextField(verbose_name='Условия транспортировки')),
                ('initial_bet', models.FloatField(verbose_name='Начальная ставка')),
                ('currency', models.CharField(choices=[('USD', 'Доллары'), ('EUR', 'Евро'), ('UZS', 'Сум'), ('RUB', 'Рубли'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена')], max_length=3, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': ' ',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('telephone_num', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
                ('comp_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.BooleanField(default=False, verbose_name='Подтвержден')),
            ],
            options={
                'verbose_name': ' ',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='Начало')),
                ('finish_date', models.DateTimeField(verbose_name='Конец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('parameters', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.parameters', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': ' ',
                'verbose_name_plural': 'Лоты',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('lot', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bot.lot', verbose_name='Лот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': ' ',
                'verbose_name_plural': 'Ставки',
            },
        ),
    ]
