# Generated by Django 5.0 on 2023-12-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('comment', models.TextField()),
                ('date_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure', models.TextField()),
                ('destination', models.TextField()),
                ('volume', models.FloatField()),
                ('weight', models.FloatField()),
                ('is_danger', models.BooleanField()),
                ('description', models.TextField()),
                ('conditions', models.CharField(max_length=255)),
                ('initial_bet', models.FloatField()),
                ('currency', models.IntegerField()),
                ('del_time', models.IntegerField()),
                ('created_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.IntegerField()),
                ('finish_date', models.IntegerField()),
                ('last_bet_id', models.FloatField()),
                ('created_at', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('bets', models.ManyToManyField(to='bot.bet')),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.parameters')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user'),
        ),
    ]
