# Generated by Django 5.0.1 on 2024-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='isViewed',
            field=models.BooleanField(default=False),
        ),
    ]
