# Generated by Django 5.0 on 2023-12-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_bet_comment_alter_tguser_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='lot',
        ),
        migrations.AddField(
            model_name='lot',
            name='parameters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.parameters', verbose_name='Параметры'),
        ),
    ]
