# Generated by Django 5.0.1 on 2024-02-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_isviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='setep',
            field=models.IntegerField(default=10, help_text='Интервал ставок - по умолчанию 10 у.е', verbose_name='Шаг ставки'),
        ),
    ]
