# Generated by Django 5.0.1 on 2024-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_lot_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, null=True, to='bot.tguser'),
        ),
    ]
