# Generated by Django 5.0.1 on 2024-02-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Отправляться не будет', max_length=255, verbose_name='Название анонса')),
                ('message_text', models.FloatField(verbose_name='Текст')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': ' ',
                'verbose_name_plural': 'Анонсы',
            },
        ),
    ]
