# Generated by Django 5.0.1 on 2024-02-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='message_text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
