# Generated by Django 5.0.1 on 2024-02-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_announcements_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='img',
        ),
        migrations.AddField(
            model_name='announcements',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
