# Generated by Django 5.0.1 on 2024-02-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_announcements_img_announcements_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='photo',
            new_name='img',
        ),
    ]
