# Generated by Django 4.2.9 on 2024-02-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_photo_announcements_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
