# Generated by Django 5.0.1 on 2024-02-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
