# Generated by Django 5.0.1 on 2024-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_lot_allowed_users'),
        ('notifications', '0009_custompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='allowed_users',
            field=models.ManyToManyField(help_text='Выберите пользователей допущенных до Лота', to='bot.tguser', verbose_name='Пользователи'),
        ),
    ]
